// <auto-generated />
namespace _1.Local_Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedQuantityAndWeight : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedQuantityAndWeight));
        
        string IMigrationMetadata.Id
        {
            get { return "201710121532168_AddedQuantityAndWeight"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
